# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leancamp

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Simple Jekyll theme to host internal/external events happening in and around your area. Free free to contribute or fork the repo.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leancamp.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /:title.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
formbox-url: "https://formbox.es/ur7fa7Zq3wuDX8G4gn2Xwegv"
